apiVersion: v1
kind: ConfigMap
metadata:
  name: config-service-config
data:
  GitOptions.yaml: |-
    giturl: 'https://github.com/simonjaeger/contoso.git'
    localrepositorypath: '/app/'
    gitmail: 'peter_bryntesson@hotmail.com'
    gituser: 'peterbryntesson'
    gitpassword: '...'
    gitbranch: 'main'