apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: LoadBalancer
  selector:
    app: config-service
  ports:
  - port: 4080
    name: http
    targetPort: 80
    protocol: TCP
  - port: 443
    name: https
    targetPort: 443
    protocol: TCP